name: motel_booking_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  flutter_config: ^2.0.2
  google_maps_flutter: ^2.4.0
  hooks_riverpod: ^2.3.7
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  #flutter_gen_runner: ^5.3.1
  riverpod_generator: ^2.2.4


flutter:
  uses-material-design: true


  assets:
    - assets/
    
    
                                      